name: End-to-end tests
on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  e2e_tests:
    # Avoid to run the job twice, once on PR merge and once on the fact that this
    # merge-event is also a push to the master branch
    if: github.event.pull_request.merged == false
    name: Run unit tests
    runs-on: ubuntu-22.04
    steps:
    # Install plaquette-ibm-backend
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'requirements*.txt'
    - name: Install Python packages
      run: python3 -m pip install -r requirements_dev.txt -r requirements.txt
    # setup-python creates an empty venv and wants to know about
    # requirements.txt, but it does not install any packages from it.
    - name: Build plaquette-ibm-backend
      run: python3 -m build --wheel
    - name: Install plaquette-ibm-backend
      run: pip install dist/plaquette_ibm_backend*.whl
    - name: Run end-to-end tests
      run: python -m pytest -m "e2e"
      env:
        IBM_TOKEN: ${{ secrets.IBM_TOKEN }}
