on:
  push:
    tags: ['*']
  workflow_dispatch:
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/plaquette-ibm-backend
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install build requirements
        run: pip install -U build setuptools
      - name: Build wheels
        run: python -m build -w
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
